// <auto-generated />
using AnimalShelter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelter.Migrations
{
    [DbContext(typeof(AnimalShelterContext))]
    partial class AnimalShelterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalShelter.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Breed")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Species")
                        .IsRequired();

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 3,
                            Breed = "Calico",
                            Name = "Mouse",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 13,
                            Breed = "Terrier",
                            Name = "Tookie",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = 8,
                            Breed = "Mini",
                            Name = "Guy",
                            Species = "Horse"
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = 57,
                            Breed = "Diamondback",
                            Name = "Mr. Bigglesworth",
                            Species = "Turtle"
                        },
                        new
                        {
                            AnimalId = 5,
                            Age = 2,
                            Breed = "Mini Lop",
                            Name = "Sandy",
                            Species = "Bunny"
                        },
                        new
                        {
                            AnimalId = 6,
                            Age = 5,
                            Breed = "Goldendoodle",
                            Name = "Celine Dion",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 7,
                            Age = 16,
                            Breed = "Sphynx",
                            Name = "Nood",
                            Species = "Cat"
                        });
                });

            modelBuilder.Entity("AnimalShelter.Models.Shelter", b =>
                {
                    b.Property<int>("ShelterId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("State")
                        .IsRequired();

                    b.HasKey("ShelterId");

                    b.ToTable("Shelters");

                    b.HasData(
                        new
                        {
                            ShelterId = 1,
                            City = "Portland",
                            Name = "Pups N' Stuff",
                            State = "Oregon"
                        },
                        new
                        {
                            ShelterId = 2,
                            City = "Santa Cruz",
                            Name = "YSPCA",
                            State = "California"
                        },
                        new
                        {
                            ShelterId = 3,
                            City = "Boise",
                            Name = "The Animal Shelter",
                            State = "Idaho"
                        },
                        new
                        {
                            ShelterId = 4,
                            City = "Troutdale",
                            Name = "PetCo",
                            State = "Oregon"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
